spring:
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


project:
  poster: posters/

base:
  url: "http://localhost:8080"